/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AImage: typeof import('ant-design-vue/es')['Image']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATimeRangePicker: typeof import('ant-design-vue/es')['TimeRangePicker']
    CalendarColorBar: typeof import('./src/components/CalendarColorBar.vue')['default']
    CalendarDDLCard: typeof import('./src/components/CalendarDDLCard.vue')['default']
    CalendarTimePeriod: typeof import('./src/components/CalendarTimePeriod.vue')['default']
    CalendarTimePoint: typeof import('./src/components/CalendarTimePoint.vue')['default']
    CoordinateLineCom: typeof import('./src/components/CoordinateLineCom.vue')['default']
    CoordinatePointCom: typeof import('./src/components/CoordinatePointCom.vue')['default']
    MapEditor: typeof import('./src/components/MapEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimeDisplayCom: typeof import('./src/components/TimeDisplayCom.vue')['default']
    TimePeriodEventAdd: typeof import('./src/components/TimePeriodEventAdd.vue')['default']
    TimePeriodEventModify: typeof import('./src/components/TimePeriodEventModify.vue')['default']
    TimePointEventAdd: typeof import('./src/components/TimePointEventAdd.vue')['default']
    TimePointEventModify: typeof import('./src/components/TimePointEventModify.vue')['default']
  }
}
